/**
 * Mock Data for MVP Development
 * This file contains mock data for testing without database
 */

// Note: uuid will be used when connecting to real database
// For MVP, we use hardcoded IDs

// Mock Seller 1: Registered Individual Merchant
export const mockSeller1 = {
  account: {
    id: 'seller-1-account-id',
    user_id: 'seller-1-user-id',
    app_id: 'allkons-m',
    allkons_id: 'ALK-SELLER-001',
    customer_code: 'SELLER-001',
    customer_profile_type: 'PERSONAL',
    customer_status: 'CUSTOMER',
    juristic_name: 'ร้านวัสดุก่อสร้างสมชาย',
    juristic_type_id: null, // Registered Individual Merchant
    organize_type: 'HEAD_OFFICE',
    tax_id: '1234567890123',
    branch_number: null,
    contact_shown_highest_authority: false,
    is_dopa: true,
    is_dbd: false,
    kyc_status: 'APPROVE',
    active_status: true,
    phone_number: '0812345678',
    email: 'seller1@example.com',
  },
  organization: {
    id: 'seller-1-org-id',
    account_id: 'seller-1-account-id',
    allkons_org_id: 'ALK-ORG-001',
    organization_code: 'ORG-001',
    name: 'ร้านวัสดุก่อสร้างสมชาย',
    name_en: 'Somchai Construction Materials',
    juristic_name: 'ร้านวัสดุก่อสร้างสมชาย',
    juristic_type_id: 'registered-individual-id', // REGISTERED_INDIVIDUAL
    organize_type: 'HEAD_OFFICE',
    tax_id: '1234567890123',
    branch_number: null,
    business_registration_number: 'BR-001',
    contact_shown_highest_authority: false,
    is_dopa: true,
    is_dbd: false,
    kyb_status: 'APPROVE',
    is_verified: true,
    active_status: true,
  },
  shop: {
    id: 'seller-1-shop-id',
    organization_id: 'seller-1-org-id',
    subdomain: 'somchai',
    name: 'ร้านวัสดุก่อสร้างสมชาย',
    name_en: 'Somchai Construction Materials',
    description: 'จำหน่ายวัสดุก่อสร้างคุณภาพ',
    logo_url: null,
    banner_url: null,
    theme_color: '#00af43',
    is_active: true,
  },
  branches: [
    {
      id: 'seller-1-branch-1-id',
      shop_id: 'seller-1-shop-id',
      name: 'สำนักงานใหญ่',
      name_en: 'Head Office',
      address_line1: '123 ถนนสุขุมวิท',
      address_line2: 'แขวงคลองตัน',
      city: 'กรุงเทพมหานคร',
      province: 'กรุงเทพมหานคร',
      postal_code: '10110',
      phone_number: '02-123-4567',
      email: 'headoffice@somchai.com',
      is_main: true,
      is_active: true,
    },
    {
      id: 'seller-1-branch-2-id',
      shop_id: 'seller-1-shop-id',
      name: 'สาขา 1',
      name_en: 'Branch 1',
      address_line1: '456 ถนนพหลโยธิน',
      address_line2: 'แขวงจตุจักร',
      city: 'กรุงเทพมหานคร',
      province: 'กรุงเทพมหานคร',
      postal_code: '10900',
      phone_number: '02-234-5678',
      email: 'branch1@somchai.com',
      is_main: false,
      is_active: true,
    },
  ],
};

// Mock Seller 2: Legal Entity
export const mockSeller2 = {
  account: {
    id: 'seller-2-account-id',
    user_id: 'seller-2-user-id',
    app_id: 'allkons-m',
    allkons_id: 'ALK-SELLER-002',
    customer_code: 'SELLER-002',
    customer_profile_type: 'PERSONAL',
    customer_status: 'CUSTOMER',
    juristic_name: 'บริษัทวัสดุก่อสร้าง จำกัด',
    juristic_type_id: 'limited-company-id', // LIMITED_COMPANY
    organize_type: 'HEAD_OFFICE',
    tax_id: '9876543210987',
    branch_number: null,
    contact_shown_highest_authority: true,
    is_dopa: true,
    is_dbd: true,
    kyc_status: 'APPROVE',
    active_status: true,
    phone_number: '0823456789',
    email: 'seller2@example.com',
  },
  organization: {
    id: 'seller-2-org-id',
    account_id: 'seller-2-account-id',
    allkons_org_id: 'ALK-ORG-002',
    organization_code: 'ORG-002',
    name: 'บริษัทวัสดุก่อสร้าง จำกัด',
    name_en: 'Construction Materials Co., Ltd.',
    juristic_name: 'บริษัทวัสดุก่อสร้าง จำกัด',
    juristic_type_id: 'limited-company-id', // LIMITED_COMPANY
    organize_type: 'HEAD_OFFICE',
    tax_id: '9876543210987',
    branch_number: null,
    business_registration_number: 'BR-002',
    contact_shown_highest_authority: true,
    is_dopa: true,
    is_dbd: true,
    kyb_status: 'APPROVE',
    is_verified: true,
    active_status: true,
  },
  shop: {
    id: 'seller-2-shop-id',
    organization_id: 'seller-2-org-id',
    subdomain: 'construction-materials',
    name: 'บริษัทวัสดุก่อสร้าง จำกัด',
    name_en: 'Construction Materials Co., Ltd.',
    description: 'ผู้จำหน่ายวัสดุก่อสร้างชั้นนำ',
    logo_url: null,
    banner_url: null,
    theme_color: '#00af43',
    is_active: true,
  },
  branches: [
    {
      id: 'seller-2-branch-1-id',
      shop_id: 'seller-2-shop-id',
      name: 'สำนักงานใหญ่',
      name_en: 'Head Office',
      address_line1: '789 ถนนรัชดาภิเษก',
      address_line2: 'แขวงห้วยขวาง',
      city: 'กรุงเทพมหานคร',
      province: 'กรุงเทพมหานคร',
      postal_code: '10320',
      phone_number: '02-345-6789',
      email: 'info@construction-materials.com',
      is_main: true,
      is_active: true,
    },
    {
      id: 'seller-2-branch-2-id',
      shop_id: 'seller-2-shop-id',
      name: 'สาขา 1',
      name_en: 'Branch 1',
      address_line1: '321 ถนนบางนา-ตราด',
      address_line2: 'แขวงบางนา',
      city: 'กรุงเทพมหานคร',
      province: 'กรุงเทพมหานคร',
      postal_code: '10260',
      phone_number: '02-456-7890',
      email: 'branch1@construction-materials.com',
      is_main: false,
      is_active: true,
    },
  ],
};

// Mock Products (for Buyer Marketplace - Guest Mode)
export const mockProducts = [
  {
    id: 'product-1',
    shop_id: 'seller-1-shop-id',
    shop_name: 'ร้านวัสดุก่อสร้างสมชาย',
    master_sku_id: 'msku-001',
    name: 'ปูนซีเมนต์ปอร์ตแลนด์ ตราช้าง 50 กก.',
    name_en: 'Portland Cement Elephant Brand 50kg',
    description: 'ปูนซีเมนต์คุณภาพสูง สำหรับงานก่อสร้างทั่วไป',
    price: 185.00,
    special_price: null,
    image_url: null,
    category: 'ปูนและซีเมนต์',
    brand: 'ตราช้าง',
    stock_status: 'STOCKED',
    is_active: true,
  },
  {
    id: 'product-2',
    shop_id: 'seller-1-shop-id',
    shop_name: 'ร้านวัสดุก่อสร้างสมชาย',
    master_sku_id: 'msku-002',
    name: 'อิฐมอญ 1 ก้อน',
    name_en: 'Clay Brick 1 piece',
    description: 'อิฐมอญคุณภาพดี สำหรับงานก่อสร้าง',
    price: 3.50,
    special_price: 3.00,
    image_url: null,
    category: 'อิฐและบล็อก',
    brand: 'ท้องถิ่น',
    stock_status: 'STOCKED',
    is_active: true,
  },
  {
    id: 'product-3',
    shop_id: 'seller-2-shop-id',
    shop_name: 'บริษัทวัสดุก่อสร้าง จำกัด',
    master_sku_id: 'msku-003',
    name: 'เหล็กเสริมคอนกรีต SD40 12 มม.',
    name_en: 'Reinforcing Steel SD40 12mm',
    description: 'เหล็กเสริมคอนกรีตมาตรฐาน SD40',
    price: 285.00,
    special_price: null,
    image_url: null,
    category: 'เหล็กและโลหะ',
    brand: 'มาตรฐาน',
    stock_status: 'STOCKED',
    is_active: true,
  },
  {
    id: 'product-4',
    shop_id: 'seller-2-shop-id',
    shop_name: 'บริษัทวัสดุก่อสร้าง จำกัด',
    master_sku_id: 'msku-004',
    name: 'กระเบื้องเซรามิก 30x30 ซม.',
    name_en: 'Ceramic Tile 30x30 cm',
    description: 'กระเบื้องเซรามิกคุณภาพดี',
    price: 45.00,
    special_price: 39.00,
    image_url: null,
    category: 'กระเบื้องและหิน',
    brand: 'ท้องถิ่น',
    stock_status: 'STOCKED',
    is_active: true,
  },
];

// Mock phone numbers for testing
export const MOCK_PHONE_NUMBERS = {
  SELLER_1: '0812345678',
  SELLER_2: '0823456789',
  ADMIN: '0834567890',
};

// Mock OTP codes for testing (development only)
export const MOCK_OTP_CODES = {
  [MOCK_PHONE_NUMBERS.SELLER_1]: '123456',
  [MOCK_PHONE_NUMBERS.SELLER_2]: '234567',
  [MOCK_PHONE_NUMBERS.ADMIN]: '345678',
};
